// <auto-generated />
using System;
using System.Text.Json;
using Fennec.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fennec.Api.Migrations
{
    [DbContext(typeof(FennecDbContext))]
    [Migration("20260306205108_AddServerGroupsAndChannels")]
    partial class AddServerGroupsAndChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fennec.Api.Models.AuthMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_method");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_method_user_id");

                    b.ToTable("auth_method", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_group_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channel");

                    b.HasIndex("ChannelGroupId")
                        .HasDatabaseName("ix_channel_channel_group_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_channel_server_id");

                    b.ToTable("channel", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.ChannelGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channel_group");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_channel_group_server_id");

                    b.ToTable("channel_group", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_server_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_server_slug");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.ServerMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_server_member");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_member_server_id");

                    b.HasIndex("UserId", "ServerId")
                        .IsUnique()
                        .HasDatabaseName("ix_server_member_user_id_server_id");

                    b.ToTable("server_member", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_session_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_local");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_name");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Fennec.Api.Models.AuthMethod", b =>
                {
                    b.HasOne("Fennec.Api.Models.User", "User")
                        .WithMany("AuthMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_method_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fennec.Api.Models.Channel", b =>
                {
                    b.HasOne("Fennec.Api.Models.ChannelGroup", "ChannelGroup")
                        .WithMany("Channels")
                        .HasForeignKey("ChannelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_channel_group_channel_group_id");

                    b.HasOne("Fennec.Api.Models.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_server_server_id");

                    b.Navigation("ChannelGroup");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Fennec.Api.Models.ChannelGroup", b =>
                {
                    b.HasOne("Fennec.Api.Models.Server", "Server")
                        .WithMany("ChannelGroups")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_group_server_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Fennec.Api.Models.ServerMember", b =>
                {
                    b.HasOne("Fennec.Api.Models.Server", "Server")
                        .WithMany("Members")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_member_server_server_id");

                    b.HasOne("Fennec.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_member_user_user_id");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fennec.Api.Models.Session", b =>
                {
                    b.HasOne("Fennec.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fennec.Api.Models.ChannelGroup", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Fennec.Api.Models.Server", b =>
                {
                    b.Navigation("ChannelGroups");

                    b.Navigation("Channels");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Fennec.Api.Models.User", b =>
                {
                    b.Navigation("AuthMethods");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
