### Register a user
POST https://localhost:7014/api/v1/auth/register
Content-Type: application/json

{
  "name": "juce",
  "displayName": "juce",
  "password": "a"
}

### Login
POST https://localhost:7014/api/v1/auth/login
Content-Type: application/json

{
  "name": "juce",
  "password": "a"
}

### Get a public token
POST https://localhost:7014/api/v1/auth/public-token
Authorization: Session 2/5MalYxaDstXKjEc3Kqr4LPJrKm04lTF7jOLIrANiwn4vt1BXO8erWbsr05h9YjN7HO+Lr1GkF5bxwPh0lo3w==
Content-Type: application/json

{
  "audience": "https://localhost:7014"
}

