### Register a user
POST https://localhost:7014/api/v1/auth/register
Content-Type: application/json

{
  "name": "karo",
  "password": "a"
}

### Login
POST https://localhost:7014/api/v1/auth/login
Content-Type: application/json

{
  "name": "karo",
  "password": "a"
}

### Get a public token
POST https://localhost:7014/api/v1/auth/public-token
Authorization: Session c9j5ADKAevrQq/S/nUrjlINa8/Z/W1WMFZ6I8KYjlk0VF/JAgCMyBNKeu06wVPHcc+aBCawrEZZfCI0h+/APmA==
Content-Type: application/json

{
  "audience": "https://localhost:7014"
}
