### Register a user
POST https://localhost:7014/api/v1/auth/register
Content-Type: application/json

{
  "name": "karo",
  "password": "a"
}

### Login
POST https://localhost:7014/api/v1/auth/login
Content-Type: application/json

{
  "name": "karo",
  "password": "a"
}

### Get a public token
POST https://localhost:7014/api/v1/auth/public-token
Authorization: Session YZnmi4f9swpzDP+kKc7TIxZWKqJPP6nr9498GIbXRYGsRGRKr74Gahs77J5eI/NMMVNBJQ9XKBIiIC7CxjWSnw==
Content-Type: application/json

{
  "audience": "https://localhost:7014"
}
