### Create a server
POST https://localhost:7014/api/v1/server/create
Content-Type: application/json
Authorization: {{bearer}}

{
  "name": "beanland",
  "visibility": 0
}

### Join a server
POST https://localhost:7014/api/v1/server/join
Content-Type: application/json
Authorization: {{bearer}}

{
  "serverId": "d522680c-e43f-4632-8132-893cdcd313b7",
  "instanceUrl": "https://localhost:7014"
}

### Get joined servers
GET https://localhost:7014/api/v1/server/joined
Authorization: {{bearer}}
