apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fennec-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: fennec
            - name: POSTGRES_PASSWORD
              value: fennec
            - name: POSTGRES_DB
              value: fennec
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fennec-test
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
