### Register a user
POST https://localhost:7014/api/v1/auth/register
Content-Type: application/json

{
  "name": "karo",
  "password": "a"
}

### Login
POST https://localhost:7014/api/v1/auth/login
Content-Type: application/json

{
  "name": "karo",
  "password": "a"
}

### Get a public token
POST https://localhost:7014/api/v1/auth/public-token
Authorization: Session WQuwxKZMuf6X94S3jjTG3Pj2zHP0wHAXPG7qJ/QNz1kJy/yZTq16hKjXGgdEB7yGvmIF46H02sbC4b6MVwuI1w==
