### Create a server
POST https://localhost:7014/api/v1/server/create
Content-Type: application/json
Authorization: {{bearer}}

{
  "name": "fennec",
  "visibility": 0
}

### Join a server
POST https://localhost:7014/api/v1/server/195d0a5c-f1c8-46c1-85f0-88908511166c/join
Authorization: {{bearer}}